apiVersion: apps/v1
kind: Deployment
metadata:
  name: parse-deployment
  labels:
    app: parse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parse
  template:
    metadata:
      labels:
        app: parse
    spec:
      containers:
      - name: parse
        image: heeropunjabi/parse-server:0.3
        ports:
        - containerPort: 1337
        env:
        - name: MONGO_USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password 
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: parse-service
spec:
  type: NodePort
  selector:
    app: parse
  ports:
    - protocol: TCP
      port: 1337
      targetPort: 1337
      nodePort: 30100
